name: test

on:
  push:
    branches:
      - multi

jobs:
  test-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Composite Action
        uses: ./.github/actions/composite-action
